# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tutorial_python_nordeste_2023',
                'doc_host': 'https://paola-rodrigues.github.io',
                'git_url': 'https://github.com/paola-rodrigues/tutorial_python_nordeste_2023',
                'lib_path': 'tutorial_python_nordeste_2023'},
  'syms': { 'tutorial_python_nordeste_2023.core': { 'tutorial_python_nordeste_2023.core.foo': ( 'core.html#foo',
                                                                                                'tutorial_python_nordeste_2023/core.py')}}}
